import { IMAGES } from '@/lib/constants/paths'
import { SERVICES } from '@/lib/constants/services'

export const PROJECT_TYPES = {
  PROPOSAL: 'proposal',
  CASE_STUDY: 'caseStudy',
  NORMAL: 'normal',
} as const

export type ProjectType = (typeof PROJECT_TYPES)[keyof typeof PROJECT_TYPES]

export const PROJECTS = {
  ZENTRO: {
    CLIENT: 'Zentro',
    TYPE: PROJECT_TYPES.NORMAL,
    SERVICES: [
      SERVICES.WEB_DEV.SUBSERVICES.SAAS.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.FULL_PAGE_DEV.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.UI_UX_DESIGN.TITLE,
      SERVICES.BRAND.SUBSERVICES.VISUAL_IDENTITY.TITLE,
      SERVICES.BRAND.SUBSERVICES.NAMING.TITLE,
    ],
    IMAGES: IMAGES.PROJECTS.ZENTRO,
  },
  THE_CHOICE_UIUX_DESIGN_WEBSITE: {
    CLIENT: 'The Choice',
    TYPE: PROJECT_TYPES.CASE_STUDY,

    SERVICES: [
      SERVICES.WEB_DEV.SUBSERVICES.UI_UX_DESIGN.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.FULL_PAGE_DEV.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.SEO.TITLE,
    ],
    IMAGES: IMAGES.PROJECTS.THE_CHOICE,
  },
  DESIGN_SYSTEM: {
    CLIENT: 'Software as a Service (SaaS)',
    TYPE: PROJECT_TYPES.NORMAL,

    SERVICES: [
      SERVICES.BRAND.SUBSERVICES.DESIGN_SYSTEM.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.FULL_PAGE_DEV.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.UI_UX_DESIGN.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.COMPONENTES.TITLE,
    ],
    IMAGES: IMAGES.PROJECTS.DESIGN_SYSTEM,
  },
  VIVET_REBRANDING: {
    CLIENT: 'VIVET',
    TYPE: PROJECT_TYPES.PROPOSAL,

    SERVICES: [
      SERVICES.BRAND.SUBSERVICES.REBRANDING.TITLE,
      SERVICES.BRAND.SUBSERVICES.VISUAL_IDENTITY.TITLE,
      SERVICES.MARKETING.SUBSERVICES.SOCIAL_MEDIA_POSTS.TITLE,
      SERVICES.MARKETING.SUBSERVICES.PACKAGING.TITLE,
      SERVICES.MARKETING.SUBSERVICES.VIDEO_EDITING.TITLE,
    ],
    IMAGES: IMAGES.PROJECTS.VIVET,
  },
  ATPROY_BRAND_REFRESH: {
    CLIENT: 'Grupo ATProy',
    TYPE: PROJECT_TYPES.NORMAL,

    SERVICES: [
      SERVICES.BRAND.SUBSERVICES.BRAND_REFRESH.TITLE,
      SERVICES.BRAND.SUBSERVICES.VISUAL_IDENTITY.TITLE,
      SERVICES.MARKETING.SUBSERVICES.MOTION_GRAPHICS.TITLE,
      SERVICES.MARKETING.SUBSERVICES.FLYERS.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.FULL_PAGE_DEV.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.SEO.TITLE,
    ],
    IMAGES: IMAGES.PROJECTS.ATPROY,
  },
  ICPSJ_BRANDING: {
    CLIENT: 'La Presencia del Señor Jesús',
    TYPE: PROJECT_TYPES.NORMAL,
    SERVICES: [
      SERVICES.BRAND.SUBSERVICES.BRANDING.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.FULL_PAGE_DEV.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.SEO.TITLE,
      SERVICES.MARKETING.SUBSERVICES.MOTION_GRAPHICS.TITLE,
      SERVICES.MARKETING.SUBSERVICES.SOCIAL_MEDIA_POSTS.TITLE,
      SERVICES.MARKETING.SUBSERVICES.COPYWRITING.TITLE,
    ],
    IMAGES: IMAGES.PROJECTS.ICPSJ,
  },

  BONZER_BRANDING: {
    CLIENT: 'Bonzer',
    TYPE: PROJECT_TYPES.NORMAL,

    SERVICES: [
      SERVICES.BRAND.SUBSERVICES.BRANDING.TITLE,
      SERVICES.BRAND.SUBSERVICES.VISUAL_IDENTITY.TITLE,
      SERVICES.MARKETING.SUBSERVICES.SOCIAL_MEDIA_POSTS.TITLE,
      SERVICES.MARKETING.SUBSERVICES.PACKAGING.TITLE,
      SERVICES.MARKETING.SUBSERVICES.COPYWRITING.TITLE,
    ],
    IMAGES: IMAGES.PROJECTS.BONZER,
  },
  ICEMENE_REBRANDING: {
    CLIENT: 'ICEMENE',
    TYPE: PROJECT_TYPES.PROPOSAL,

    SERVICES: [
      SERVICES.BRAND.SUBSERVICES.REBRANDING.TITLE,
      SERVICES.BRAND.SUBSERVICES.BRAND_STRATEGY.TITLE,
      SERVICES.BRAND.SUBSERVICES.VISUAL_IDENTITY.TITLE,
    ],
    IMAGES: IMAGES.PROJECTS.ICEMENE,
  },
  THEPRINCIPAL_BRANDING: {
    CLIENT: 'ThePrincipal',
    TYPE: PROJECT_TYPES.NORMAL,

    SERVICES: [
      SERVICES.BRAND.SUBSERVICES.BRANDING.TITLE,
      SERVICES.BRAND.SUBSERVICES.VISUAL_IDENTITY.TITLE,
      SERVICES.MARKETING.SUBSERVICES.COPYWRITING.TITLE,
      SERVICES.WEB_DEV.SUBSERVICES.UI_UX_DESIGN.TITLE,
    ],
    IMAGES: IMAGES.PROJECTS.THEPRINCIPAL,
  },

  SOLAR_GROUP_REBRANDING: {
    CLIENT: 'Solar Group Guatemala',
    TYPE: PROJECT_TYPES.PROPOSAL,

    SERVICES: [SERVICES.BRAND.SUBSERVICES.VISUAL_IDENTITY.TITLE],
    IMAGES: IMAGES.PROJECTS.SOLAR_GROUP,
  },
}
